### ISSUE TITLE
目录过多以后就打不开文件了

### ISSUE THREAD

**Issue by ycg000344** [huangjianke/Gitter#10]
像java项目的层级目录外面的一些可以打开，里面目录的文件就打不开了。

**来自GitHub小程序客户端：**

![image](https://user-images.githubusercontent.com/8692455/51429898-b159f400-1c4e-11e9-91a1-59cd1fab5042.png)

**Comment by huangjianke** [comment]
目前微信小程序页面栈限制最多10级，目前还没有很好的处理方法，后续会继续关注这个问题的

感谢支持





**来自GitHub小程序客户端：**

![image](https://user-images.githubusercontent.com/8692455/51429898-b159f400-1c4e-11e9-91a1-59cd1fab5042.png)

**Comment by ycg000344** [comment]
@huangjianke 明白，找到了好久github相关的客户端了，感谢您的贡献。

**Comment by zeromake** [comment]
@huangjianke 可以考虑到了项目里面就不要做页面栈了，直接放个文件目录来跳转，或者通过内存直接存储每个页面的历史，只保留一定数量的页面栈。

**Comment by huangjianke** [comment]
@zeromake 感谢建议，我先试试
