### ISSUE TITLE
能否在Activity页面增添项目描述文字？

### ISSUE THREAD

**Issue by Grizzy-bear** [huangjianke/Gitter#18]
只看star了某个项目，但是看不到项目是做什么的，可否请作者增添描述性的文字？

**Comment by huangjianke** [comment]
![image](https://user-images.githubusercontent.com/8692455/52130966-99369b80-2676-11e9-9da3-4ada8f41c166.png)

抱歉，这是由于GitHub相关的接口提供的字段有限
