### ISSUE TITLE
您好，关于小程序域名备案问题

### ISSUE THREAD

**Issue by lai-bluejay** [huangjianke/Gitter#21]
我看代码里面访问了：
github.com
api.github.com

我在开发者后台添加域名，提示ICP没有备案。请问在具体上线的时候是怎么实现的呢

**Comment by huangjianke** [comment]
@lai-bluejay 

之前开发者后台新增未备案的域名可以保存，现在好像确实不行了。

**Comment by lai-bluejay** [comment]
@huangjianke 也确实是未备案的域名是吗？
我以为有方案解决呢，谢谢啦。我尝试其他办法曲线救国
