### ISSUE TITLE
[多端支持] 希望能加入APP(RN端)支持

### ISSUE THREAD

**Issue by Lionad-Morotar** [huangjianke/Gitter#23]

**Comment by Lionad-Morotar** [comment]
不知是否有在考虑中或是计划内

**Comment by huangjianke** [comment]
您好，暂无这个计划的。

不过Taro是支持多端编译的，我的想法是先将小程序端尽量完善，后期争取多端支持。

感谢支持！

**Comment by Lionad-Morotar** [comment]
> 您好，暂无这个计划的。
> 
> 不过Taro是支持多端编译的，我的想法是先将小程序端尽量完善，后期争取多端支持。
> 
> 感谢支持！

我使用Taro在写自己的小程序的过程中,
由于一开始没有仔细阅读文档, 所以犯了很多页面布局上的错误, 导致转RN异常艰.
我觉得你们的界面很漂亮, 但是代码中有一些地方也没有按照官网的建议写,
所以很好奇你们之后的解决方案~
总之感谢告知~ 已 Watch~ 😀

**Comment by huangjianke** [comment]
嗯，有机会的后续可以多交流交流
