### ISSUE TITLE
H5编译没有通过

### ISSUE THREAD

**Issue by soymikey** [huangjianke/Gitter#28]
微信小程序编译跨域。 H5编译没有通过，taro版本：1.2.15
感觉是不是classname 这个依赖不编译不通过？
![image](https://user-images.githubusercontent.com/37310671/53610893-a314d580-3c07-11e9-8aba-d181b5ca147a.png)

**Comment by huangjianke** [comment]
@soymikey 抱歉，目前阶段仅在微信小程序端编译，其他端暂时没做适配
