### ISSUE TITLE
一个建议：建议添加复制项目链接功能

### ISSUE THREAD

**Issue by murphywuwu** [huangjianke/Gitter#30]
建议添加复制项目链接功能，可以方便在其他终端或者app中查看

**来自GitHub小程序客户端：**

![image](https://user-images.githubusercontent.com/8692455/51429898-b159f400-1c4e-11e9-91a1-59cd1fab5042.png)

**Comment by huangjianke** [comment]
@murphywuwu 感谢反馈，新版正在支持复制链接，分享海报功能，敬请期待

**Comment by huangjianke** [comment]
@murphywuwu 最新版已支持，请更新体验，谢谢

**Comment by murphywuwu** [comment]
很棒 感谢🥳





**来自GitHub小程序客户端：**

![image](https://user-images.githubusercontent.com/8692455/51429898-b159f400-1c4e-11e9-91a1-59cd1fab5042.png)
