### ISSUE TITLE
关于actions调用的问题

### ISSUE THREAD

**Issue by tuoxie15** [huangjianke/Gitter#32]
在很多actions里面有很多createApiAction，这个在页面并没有调用，这个是已经实现了还是说初始化直接直接注入到props里？这些调用怎么用呢？我看你页面里面是直接请求的api.ge和api.post，并没有直接调用actions里面定义的方法，求解

//  我的仓库列表 API
export const reposListRefresh = createApiAction(REPOS_LIST_REFRESH, params => api.get(params.url, params.data))
export const reposListLoadMore = createApiAction(REPOS_LIST_LOADMORE, params => api.get(params.url, params.data))

// 获取starred repo
export const starredRepoRefresh = createApiAction(STARRED_REPO_REFRESH, params => api.get(params.url, params.data))
export const starredRepoLoadMore = createApiAction(STARRED_REPO_LOADMORE, params => api.get(params.url, params.data))

// 获取仓库详情
export const getRepo = createApiAction(REPO_INFO, params => api.get(params.url, params.data))
// 获取仓库 README.md
export const getRepoReadMe = createApiAction(REPO_README, params => api.get(params.url, params.data))

export default bindActionCreators({
  reposListRefresh,
  reposListLoadMore,
  getRepoReadMe,
  starredRepoRefresh,
  getRepo,
  starredRepoLoadMore
}, store.dispatch)

**Comment by huangjianke** [comment]
@tuoxie15 
目前只有在获取用户信息使用到了，可以看下相关代码。

**Comment by tuoxie15** [comment]
感谢你这么快的回复，吓我一跳，我以为有很牛逼的实现方式呢。。获取用户信息的userAction我也看到了，你页面中引用的import userAction from '../../actions/user'这个在actions/user中没有userAction这个呀？还是说userAction删掉了？

**Comment by huangjianke** [comment]
https://github.com/huangjianke/Gitter/blob/45a926c946c448f11b6c260bb1612c8d3989d3d4/src/pages/account/index.js#L58

在这里使用到了

**Comment by tuoxie15** [comment]
我是想知道userAction这个是哪里来的，在actions/user并没有定义userAction呀...

**Comment by huangjianke** [comment]
@tuoxie15 可以的，最底部有二维码
