### ISSUE TITLE
未找到入口 app.json 文件,或者文件读取失败,请检查后重新编译。 (anonymous) @ V

### ISSUE THREAD

**Issue by wsb0617** [huangjianke/Gitter#34]
修改了"miniprogramRoot": "./dist/wx/",还是会报引用问题。还有说的是权限组件问题？请问怎么解决
？

**Comment by wsb0617** [comment]
clone下来没有app.json文件

**Comment by huangjianke** [comment]
![image](https://user-images.githubusercontent.com/8692455/54324984-fee55280-463a-11e9-95c6-f0d8c5f10316.png)

@wsb0617 clone后，进入根目录，先编译，再用开发者工具打开

**Comment by wsb0617** [comment]
<img width="596" alt="图片" src="https://user-images.githubusercontent.com/5467640/54327700-f6dee000-4645-11e9-9d18-75b650cb1a2f.png">
<img width="336" alt="图片" src="https://user-images.githubusercontent.com/5467640/54327709-fba39400-4645-11e9-9d62-fafe8d817867.png">
请问这是为什么呢？
是taro 跟taro-UI版本的问题吗？
mac 环境下

**Comment by herseus** [comment]
mac上编译成微信小程序报错：
<img width="1007" alt="WX20190315-203417@2x" src="https://user-images.githubusercontent.com/8351576/54431579-c724fa80-4761-11e9-95da-d8c4c2d383fa.png">
请问这个怎么解决？@huangjianke

**Comment by huangjianke** [comment]
@huangjianke 有执行npm i 嘛
