### ISSUE TITLE
多个if-else编译错误

### ISSUE THREAD

**Issue by imageslr** [huangjianke/Gitter#35]
多个if-else连着的时候，会导致编译错误。taro的issue里查到这是个bug，请问你当初使用的是哪个版本的taro编译呢？

**Comment by huangjianke** [comment]
@imageslr 请问下有相关截图么，比较好定位问题

**Comment by imageslr** [comment]
抱歉，刚才传图片失败了。

回退Taro版本后编译通过了，谢谢及时回复~ 顺便问一句，请问可以分享一下UI Sketch设计稿吗？

<img width="854" alt="WechatIMG1732" src="https://user-images.githubusercontent.com/17822028/54338177-1852c280-466c-11e9-97c6-8ac6177aee61.png">
