### ISSUE TITLE
感觉加载trending list有点慢呀，希望优化一下就完美了

### ISSUE THREAD

**Issue by chenxxcc** [huangjianke/Gitter#38]
希望可以优化一下服务器带宽，现在加载资源着实有点慢，感谢您得付出，做的真的很好，特别高大上

**Comment by kezhenxu94** [comment]
@chenxxcc 可以试试这个小程序，markdown完美解析，功能最全，https://github.com/kezhenxu94/mini-github 
微信搜索 GitHub专业版
