### ISSUE TITLE
数据库需要如何建立

### ISSUE THREAD

**Issue by MakerGYT** [huangjianke/Gitter#39]
{"errorCode":1,"errorMessage":"user code exception caught","stackTrace":"errCode: -502005 database collection not exists | errMsg: [ResourceNotFound] Db or Table not exist. Please check your request, but if the problem cannot be solved, contact us.; "}

**Comment by huangjianke** [comment]
![image](https://user-images.githubusercontent.com/8692455/56104092-d10c6a00-5f68-11e9-8dae-0f9ef74520bd.png)
目前有用到这些数据库，需要在云开发后台创建
