### ISSUE TITLE
api 请求资源不存在 empty

### ISSUE THREAD

**Issue by MakerGYT** [huangjianke/Gitter#40]
打开pages/repo/repo
api 请求资源不存在 empty
 {"model":"iPhone 5","pixelRatio":2,"windowWidth":320,"windowHeight":504,"system":"iOS 10.0.1","language":"en","version":"6.6.3","screenWidth":320,"screenHeight":568,"SDKVersion":"2.5.1","brand":"devtools","fontSizeSetting":16,"batteryLevel":100,"statusBarHeight":20,"platform":"devtools"}

**Comment by huangjianke** [comment]
https://developer.github.com/v3/activity/starring/#check-if-you-are-starring-a-repository

@MakerGYT 可以看下GitHub的api文档，在进入repo页面时，会调用这个接口判断是否已经star了，如果没有star会返回 404
