### ISSUE TITLE
请问 basic authentication 的原理？

### ISSUE THREAD

**Issue by dpyzo0o** [huangjianke/Gitter#42]
![Screenshot 2019-04-29 at 21 53 14](https://user-images.githubusercontent.com/24768249/56922727-34e67500-6ac9-11e9-80b2-2309449299db.png)
 
![Screenshot 2019-04-29 at 21 54 27](https://user-images.githubusercontent.com/24768249/56922818-60695f80-6ac9-11e9-9715-03d006bf6bf0.png)

关于使用用户名密码进行认证的方式，看到您代码中对用户名密码进行加密，然后放在 header 中就可以通过 github 的认证。但是在 v3 的文档中，basic authentication via username and password 只给了个 curl 的例子，并没有提到通过设置 header 的方式。想请问一下，您是如何知道可以使用这种方式的呢？

**Comment by huangjianke** [comment]
@dpyzo0o 我也是通过查阅资料得知的

![image](https://user-images.githubusercontent.com/8692455/56938624-89273e80-6b35-11e9-8971-fb0ae91367f4.png)

https://www.ibm.com/support/knowledgecenter/en/SSGMCP_4.2.0/com.ibm.cics.ts.internet.doc/topics/dfhtl2a.html

**Comment by dpyzo0o** [comment]
@huangjianke 谢谢回复~ 原来是在这个 RFC 里面，是我看得不够仔细了。小程序做的很棒，一个小建议，是不是可以加一个 logout 的功能？

**Comment by huangjianke** [comment]
@dpyzo0o 有的啊，me --> about

**Comment by dpyzo0o** [comment]
@huangjianke 😂我又看漏了
