### ISSUE TITLE
Trending 页面 Star 和 Fork 都是0

### ISSUE THREAD

**Issue by MrHeer** [huangjianke/Gitter#60]
#### 如图所示，在 Trending 页面 Star 和 Fork 都是0，点进去正常
![IMG_20191113_102942](https://user-images.githubusercontent.com/18595761/68728324-f72ee100-0601-11ea-96e4-0963c76089e5.jpg)
![IMG_20191113_103005](https://user-images.githubusercontent.com/18595761/68728326-f8600e00-0601-11ea-90ae-bc872c4895d0.jpg)

**Comment by huangjianke** [comment]
@MrHeer 已修复 感谢反馈
