### ISSUE TITLE
好，clone下来后，安装依赖运行Provider of undefined #49

### ISSUE THREAD

**Issue by xiaoxiaosl** [huangjianke/Gitter#61]
报这样的错误
app.js:41 Uncaught TypeError: Cannot read property 'Provider' of undefined
at app.js:41
at require (VM133 WAService.js:1)
at :1:1
at HTMLScriptElement.scriptLoaded (appservice?t=1574834619056:2068)
at HTMLScriptElement.script.onload (appservice?t=1574834619056:2080)

**Comment by huangjianke** [comment]
可以提供下完整的报错截图吗

**Comment by xiaoxiaosl** [comment]
你好 @huangjianke ！我是在微信开发者工具里，运行的“yarn run dev:weapp”
![image](https://user-images.githubusercontent.com/10595660/69770307-7eb04e80-11c3-11ea-9f34-b0fef19f28e5.png)! 就出现这个错误，我'yarn'安装了所有依赖的..谢谢请帮我解决一下

**Comment by huangjianke** [comment]
看截图好像不是我这个项目的。

你把 node_modules 和 lock 文件都删掉，然后重新安装运行，最后开发者工具打开的是  **dist** 目录，而不是整个目录

**Comment by xiaoxiaosl** [comment]
@huangjianke 好的 谢谢你，我去试试

**Comment by xiaoxiaosl** [comment]
@huangjianke 你好！还是不行呢，我重新clone下来，所有依赖重新安装！安装过程和编译过程中都没有任何提示错误！
![image](https://user-images.githubusercontent.com/10595660/69771930-7824d580-11c9-11ea-9c7d-a0c06a57aa95.png)
![image](https://user-images.githubusercontent.com/10595660/69771960-9559a400-11c9-11ea-84f4-b8aee2cc82b0.png)
![image](https://user-images.githubusercontent.com/10595660/69771995-a9050a80-11c9-11ea-84f2-1d1342647dc3.png)

**Comment by xiaoxiaosl** [comment]
好了 我解决了！ @huangjianke , 是taro版本不一致导致的！现在已经可以使用了，
![image](https://user-images.githubusercontent.com/10595660/69773390-b623f880-11cd-11ea-9e0b-459908e77159.png)只是报这种错误，我自己弄一弄！ 谢谢
