### ISSUE TITLE
怎么绑定的请求域名呢

### ISSUE THREAD

**Issue by luohao8023** [huangjianke/Gitter#63]
请教一下作者，怎么把github的域名绑定到小程序合法域名的啊

**来自GitHub小程序客户端：**

![image](https://user-images.githubusercontent.com/8692455/51429898-b159f400-1c4e-11e9-91a1-59cd1fab5042.png)

**Comment by huangjianke** [comment]
@luohao8023 现在不行了，微信修改了策略，之前是可以的
