### ISSUE TITLE
请求限制问题

### ISSUE THREAD

**Issue by luohao8023** [huangjianke/Gitter#64]
您好，GitHub的API经常拒绝访问，授权了也不行，可是您线上的小程序却不怎么会出现请求失败的问题，是做了什么优化吗？

**Comment by huangjianke** [comment]
> 您好，GitHub的API经常拒绝访问，授权了也不行，可是您线上的小程序却不怎么会出现请求失败的问题，是做了什么优化吗？

没有相关的优化
