### ISSUE TITLE
Markdown解析问题

### ISSUE THREAD

**Issue by almas1992** [huangjianke/Gitter#9]
标签图标渲染的很大很大，贡献者头像有些也存在同样问题，然后代码块显示区域宽度过长，就是横向滑动可以滑很长很长一段距离

**来自GitHub小程序客户端：**

![image](https://user-images.githubusercontent.com/8692455/51429898-b159f400-1c4e-11e9-91a1-59cd1fab5042.png)

**Comment by huangjianke** [comment]
目前图片渲染这块都是按照手机屏幕宽度来的，我联系下Markdown解析库的作者，看是否能优化一下。谢谢

**Comment by almas1992** [comment]
> 目前图片渲染这块都是按照手机屏幕宽度来的，我联系下Markdown解析库的作者，看是否能优化一下。谢谢

https://github.com/kezhenxu94/mini-github 无意间发现了另一款github小程序客户端，这一款Markdown预览就挺好的
